# Generated by Django 4.0.4 on 2022-05-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_books_picture_alter_books_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePenalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
                ('boleta', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('moneda', models.CharField(max_length=50)),
                ('deposito', models.CharField(max_length=50)),
                ('dm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVigencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
                ('boleta', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('moneda', models.CharField(max_length=50)),
                ('deposito', models.CharField(max_length=50)),
                ('dm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='penalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=50)),
                ('calificacion', models.CharField(max_length=50)),
                ('has', models.CharField(max_length=50)),
                ('deuda', models.CharField(max_length=50)),
                ('deposito', models.CharField(max_length=50)),
                ('saldo', models.CharField(max_length=50)),
                ('devolucion', models.CharField(max_length=50)),
                ('dm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vigencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=50)),
                ('calificacion', models.CharField(max_length=50)),
                ('has', models.CharField(max_length=50)),
                ('deuda', models.CharField(max_length=50)),
                ('deposito', models.CharField(max_length=50)),
                ('saldo', models.CharField(max_length=50)),
                ('devolucion', models.CharField(max_length=50)),
                ('dm', models.CharField(max_length=50)),
            ],
        ),
    ]
