# Generated by Django 4.0.4 on 2022-06-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detallepenalidad_detallevigencia_penalidad_vigencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_old', models.CharField(max_length=50)),
                ('tbl_usuario_id', models.CharField(max_length=50)),
                ('tbl_colegio_departamental_id', models.CharField(max_length=50)),
                ('tbl_pais_id', models.CharField(max_length=50)),
                ('tbl_distrito_id', models.CharField(max_length=50)),
                ('cmpv', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('foto', models.CharField(max_length=50)),
                ('fecha_inscripcion', models.CharField(max_length=50)),
                ('fecha_colegiatura', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=50)),
                ('documento_fac', models.CharField(max_length=50)),
                ('nombre_fac', models.CharField(max_length=50)),
                ('direccion_fac', models.CharField(max_length=50)),
                ('nota', models.CharField(max_length=50)),
                ('ultima_cuota_old', models.CharField(max_length=50)),
                ('fecha_habilidad_temporal', models.CharField(max_length=50)),
                ('estado_colegio', models.CharField(max_length=50)),
                ('perfil', models.CharField(max_length=50)),
                ('multaelectoral', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('creado_por', models.CharField(max_length=50)),
                ('fecha_creado', models.CharField(max_length=50)),
                ('modificado_por', models.CharField(max_length=50)),
                ('fecha_modificado', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('colegioDepartamental', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
